// Auto-generated by NLS Refactor. Do not edit manually.
const { translate } = require('./nls_loader');

const nls_ts = {
  diplodoc: {
    submenu: {
      title: "diplodoc.submenu.title"
    }
  }
};

module.exports = { nls_ts, translate };